module.exports = {
  rules: {
    "@typescript-eslint/no-useless-constructor": ["error"],
    "arrow-body-style": ["error", "as-needed"],
    "capitalized-comments": [
      "warn",
      "always",
      { ignoreConsecutiveComments: true },
    ],
    "default-case": ["error", { commentPattern: "^skip\\sdefault" }],
    "default-case-last": "error",
    "default-param-last": ["error"],
    "dot-notation": ["error", { allowPattern: "^[a-z]+(_[a-z]+)+$" }],
    "max-classes-per-file": ["error", 1],
    "max-lines-per-function": [
      "error",
      { max: 50, skipBlankLines: true, skipComments: true },
    ],
    "new-cap": ["error", { capIsNewExceptionPattern: "^@*" }],
    "no-alert": "error",
    "no-console": ["warn", { allow: ["warn", "error"] }],
    "no-else-return": "error",
    "no-empty-function": ["error", { allow: ["constructors"] }],
    "no-eq-null": "error",
    "no-eval": "error",
    "no-lonely-if": "error",
    "no-loop-func": "error",
    "no-magic-numbers": ["error", { ignoreArrayIndexes: true }],
    "no-mixed-operators": ["error", { allowSamePrecedence: true }],
    "no-multi-assign": ["error", { ignoreNonDeclaration: true }],
    "no-multi-str": "error",
    "no-nested-ternary": ["warn"],
    "no-return-assign": ["error", "always"],
    "no-return-await": "error",
    "no-script-url": "error",
    "no-underscore-dangle": ["warn"],
    "no-unneeded-ternary": "error",
    "no-unused-expressions": ["warn"],
    "no-useless-return": "error",
    "no-var": "error",
    "one-var-declaration-per-line": ["error"],
    "prefer-arrow-callback": "error",
    "prefer-const": "error",
    "prefer-object-spread": "error",
    "require-await": "error",
    "spaced-comment": ["error", "always"],
    "simple-import-sort/imports": "error",
  },
};
